version: 2
jobs:
  build_master:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - checkout
      - run: npm install --silent
      - run: ./deploy/master
  build_production:
    machine:
      enabled: true
    steps:
      - add_ssh_keys
      - checkout
      - run: npm install --silent
      - run: ./deploy/production

before_script:
  - npm install gulp

workflows:
  version: 2
  build:
    jobs:
      - build_master:
          filters:
              branches:
                only: master
      - build_production:
          filters:
            branches:
              only: production
