#!/bin/bash

### CONFIGURE GIT
git config --global -l
git config --global user.name 'CircleCI'
git config --global user.email 'circle@ci'

### ANDROID
git reset --hard origin/master
sed -i '/<link rel="stylesheet"/s/ios/material/' ./www/index.html
sed -i '/<platform name="ios">/,/<\/platform>/d' ./config.xml

git add -A
git commit -m 'Automatic Android deploy'
git push -f origin master:master-android

### iOS
git reset --hard origin/master
sed -i '/<link rel="stylesheet"/s/material/ios/' ./www/index.html
sed -i '/<platform name="android">/,/<\/platform>/d' ./config.xml

git add -A
git commit -m 'Automatic iOS deploy'
git push -f origin master:master-ios
git reset --hard origin/master

### DEPLOY TO PHONEGAP BUILD
curl spindelman@fsektionen.se -X PUT -d 'data={"pull":"true"}' \
  "https://build.phonegap.com/api/v1/apps/2730428?auth_token=${phonegap_build_token}"

curl spindelman@fsektionen.se -X PUT -d 'data={"pull":"true"}' \
  "https://build.phonegap.com/api/v1/apps/2732905?auth_token=${phonegap_build_token}"
